[package]
name = "x2fa"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
futures = "0.3.25"
qr2term = "0.3.1"
tokio = { version = "1.22.0", features = ["full"] }
totp-lite = "2.0.0"
